apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-ops-view
    component: frontend
  name: kube-ops-view
  namespace: ops-view
spec:
  selector:
    application: kube-ops-view
    component: frontend
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: kube-ops-view
    component: frontend
  name: kube-ops-view
  namespace: ops-view
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: kube-ops-view
    weight: 100
  wildcardPolicy: None
